spring:
  datasource:
    username: xxx
    password: xxx
    url: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: xxx
    password: xxx
    host: smtp.qq.com
    # 开启加密验证
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: xxx
    port: 6379

server:
  port: 9000
  servlet:
    context-path: /

logging:
  level:
    com:
      lemonfish:
        mapper: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
