spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/course_table?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
  servlet:
    context-path: /

logging:
  level:
    com:
      lemonfish:
        mapper: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
