spring:
  datasource:
    username: xxxxx
    password: xxxxxx
    url: your url
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: yourmail
    password: yourpassword
    host: smtp.qq.com
    # 开启加密验证
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: yourhost
    port: 0000000

server:
  port: 9000
  servlet:
    context-path: /

logging:
  level:
    com:
      lemonfish:
        mapper: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
